/**
 * @dig/domain — shared retrieval services, business logic, and types.
 *
 * This package is imported by apps/api, apps/mcp, and apps/ingest.
 * It contains no framework-specific code — just pure domain logic
 * that operates on the DB via @dig/db.
 */

export { healthCheck } from "./health.js";
export { getBatchForTable } from "./batch.js";
export {
  search,
  validateSearchParams,
  getTimeoutStats,
  type SearchParams,
  type SearchResponse,
  type SearchResult,
  type SearchEntityType,
  type SearchError,
  type SearchTopMatch,
  type SearchTypeCounts,
} from "./search.js";
export {
  getArtist,
  getLabel,
  getMaster,
  getRelease,
  getReleaseShadow,
  type ArtistDetail,
  type LabelDetail,
  type LabelEditorial,
  type SublabelLink,
  type MasterDetail,
  type ReleaseDetail,
  type ReleaseShadow,
} from "./retrieval/index.js";
export { getCoverUrl, type CoverResult } from "./covers.js";
export {
  getArtistReleases,
  getArtistMasters,
  getArtistCatalogReleases,
  getLabelReleases,
  getLabelRoster,
  getLabelStyles,
  getArtistPrimaryLabels,
  getMasterReleases,
  getMasterVideos,
  getReleaseCredits,
  classifyReleaseType,
  classifyRoleFamily,
  expandArtistAliasIds,
  getArtistCredits,
  type TraversalResponse,
  type TraversalLink,
  type LabelMasterLink,
  type LabelRosterEntry,
  type LabelRosterResponse,
  type LabelStyleEntry,
  type LabelStylesResponse,
  type ArtistPrimaryLabelEntry,
  type MasterVideosResponse,
  type MasterVideo,
  type ReleaseType,
  type ReleaseTypeLabel,
  type RoleFamily,
  type ArtistCreditLink,
  type ArtistCreditsResponse,
} from "./traversal.js";
export {
  classifyEntityQuality,
  getSuppressedEntityKeys,
  QUALITY_VERSION,
  type QualityStatus,
  type QualityScore,
} from "./quality.js";
export {
  listScenes,
  getScene,
  getSceneWall,
  getScenePlaylist,
  type ScenePlaylist,
  type ScenePlaylistRecord,
  type SceneAxis,
  type SceneRole,
  type BridgeKind,
  type ScenePalette,
  type SceneSummary,
  type SceneLabelMember,
  type SceneBridgeLink,
  type SceneDetail,
  type WallStripRelease,
  type WallStripLabel,
  type SceneWall,
} from "./scenes.js";
export {
  getLabelCoreRun,
  getLabelRelated,
  type CoreRunMaster,
  type RelatedLabel,
  type RelatedDirection,
} from "./label-essentials.js";
export {
  getArtistRuleACredits,
  getArtistCrossScopeCredits,
  getMasterCredits,
  getArtistGroupsAndMembers,
  getArtistCollaborators,
  getArtistLabelmates,
  getLabelTopCredits,
  type ArtistMasterCredit,
  type ArtistMasterCreditsResponse,
  type CrossScopeCreditCard,
  type CrossScopeCreditsResponse,
  type MasterTrackCreditLine,
  type MasterReleaseCreditLine,
  type MasterCreditsResponse,
  type ArtistGroupEdge,
  type ArtistGroupsAndMembersResponse,
  type ArtistCollaborator,
  type ArtistCollaboratorsResponse,
  type ArtistLabelmate,
  type ArtistLabelmatesResponse,
  type LabelTopCreditEntry,
} from "./credits.js";
export {
  getEntityImages,
  getEntityImagesBulk,
  shapeCommonsUrl,
  type EntityImage,
  type EntityImagesResponse,
  type ImageKind,
  type ImageEntityType,
} from "./images.js";
export {
  getArtistRelationships,
  getArtistContext,
  getArtistTimeline,
  getLabelLinkouts,
  parseEnrichmentParams,
  validateEnrichmentParams,
  type RelationshipsResponse,
  type ContextResponse,
  type TimelineResponse,
  type TimelineEvent,
  type LabelLinkout,
  type LabelLinkoutsResponse,
  type EnrichmentParams,
  type EdgeDirection,
  type RelationshipEdge,
  type ContextBlock,
} from "./enrichment.js";
