/**
 * join-report.ts - writes docs/wine-bore-join-report.md.
 *
 * Every number is read back out of Postgres at run time: live counts from the
 * tables, per-loader rows from the newest wine.load_log row for each loader,
 * and the per-source method breakdowns from that row's notes. Nothing in the
 * output is typed by hand except the section headings and the "what would
 * move this" lines, which are quoted from the loaders' own notes.
 *
 *   DATABASE_URL=postgresql://dig:dig_local@localhost:5433/dig pnpm exec tsx scripts/wine/join-report.ts
 */
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import type pg from "pg";
import { REPO_ROOT, connect, logLoad } from "./lib";

const OUT = resolve(REPO_ROOT, "docs", "wine-bore-join-report.md");

async function q(pool: pg.Pool, sql: string, params: unknown[] = []): Promise<any[]> {
  const { rows } = await pool.query(sql, params);
  return rows;
}

function pct(n: number, d: number): string {
  return d === 0 ? "-" : `${((100 * n) / d).toFixed(1)}%`;
}

function table(head: string[], rows: Array<Array<string | number>>): string {
  const out = [`| ${head.join(" | ")} |`, `|${head.map(() => "---").join("|")}|`];
  for (const r of rows) out.push(`| ${r.join(" | ")} |`);
  return out.join("\n");
}

async function main() {
  const pool = connect();
  const L: string[] = [];

  // newest run per loader
  const logs = new Map<string, any>();
  for (const r of await q(pool, `
    SELECT loader, rows_in, rows_out, matched, unmatched, ran_at, notes
      FROM wine.load_log l
     WHERE l.id = (SELECT max(id) FROM wine.load_log x WHERE x.loader = l.loader)`)) {
    logs.set(r.loader, r);
  }
  const n = (loader: string, key: string) => {
    const r = logs.get(loader);
    return r ? (r[key] ?? "") : "";
  };
  const notes = (loader: string) => (logs.get(loader)?.notes ?? {}) as Record<string, any>;

  L.push("# Wine Bore - join report");
  L.push("");
  L.push(`Generated by \`scripts/wine/join-report.ts\` on ${new Date().toISOString().slice(0, 10)}.`);
  L.push("Every figure is read back from Postgres; none is carried over from a loader's console output.");
  L.push("");

  // ---- 1. sources -----------------------------------------------------
  L.push("## Sources");
  L.push("");
  L.push(table(["source", "name", "licence", "pulled", "demo only"],
    (await q(pool, `SELECT slug, name, coalesce(licence,'-') licence, coalesce(pulled_at::text,'-') pulled_at, demo_only FROM wine.sources ORDER BY slug`))
      .map((r) => [`\`${r.slug}\``, r.name, r.licence, r.pulled_at, r.demo_only ? "yes" : "no"])));
  L.push("");

  // ---- 2. rows in / out ----------------------------------------------
  L.push("## Rows in, rows out");
  L.push("");
  const order = [
    "load-appellations", "load-grapes", "load-appellation-documents", "load-lwin",
    "load-producer-links", "load-systembolaget", "load-wikidata-wines",
    "resolve-appellations", "resolve-wine-grapes", "search-vectors", "join-report",
  ];
  L.push(table(["loader", "rows in", "rows out", "matched", "unmatched", "last run"],
    order.filter((o) => logs.has(o)).map((o) => {
      const r = logs.get(o);
      return [`\`${o}\``, r.rows_in ?? "-", r.rows_out ?? "-", r.matched ?? "-", r.unmatched ?? "-",
        r.ran_at.toISOString().slice(0, 16).replace("T", " ")];
    })));
  L.push("");
  L.push("## Live table counts");
  L.push("");
  const counts = await q(pool, `
    SELECT 'appellations' t, count(*) c FROM wine.appellations
    UNION ALL SELECT 'appellations (EU register)', count(*) FROM wine.appellations WHERE source <> 'lwin'
    UNION ALL SELECT 'appellations (synthetic, non-EU)', count(*) FROM wine.appellations WHERE source = 'lwin'
    UNION ALL SELECT 'appellation_names', count(*) FROM wine.appellation_names
    UNION ALL SELECT 'appellation_names (kind=lwin)', count(*) FROM wine.appellation_names WHERE kind = 'lwin'
    UNION ALL SELECT 'appellation_documents', count(*) FROM wine.appellation_documents
    UNION ALL SELECT 'appellation_grapes', count(*) FROM wine.appellation_grapes
    UNION ALL SELECT 'grapes', count(*) FROM wine.grapes
    UNION ALL SELECT 'grape_names', count(*) FROM wine.grape_names
    UNION ALL SELECT 'producers', count(*) FROM wine.producers
    UNION ALL SELECT 'producer_links', count(*) FROM wine.producer_links
    UNION ALL SELECT 'wines', count(*) FROM wine.wines
    UNION ALL SELECT 'wines (Live)', count(*) FROM wine.wines WHERE status = 'Live'
    UNION ALL SELECT 'wine_names', count(*) FROM wine.wine_names
    UNION ALL SELECT 'wine_grapes', count(*) FROM wine.wine_grapes
    UNION ALL SELECT 'listings', count(*) FROM wine.listings`);
  L.push(table(["table", "rows"], counts.map((r) => [r.t, r.c])));
  L.push("");

  // ---- 3. join rates -------------------------------------------------
  L.push("## Join rates");
  L.push("");

  L.push("### Systembolaget listings");
  L.push("");
  const ls = (await q(pool, `
    SELECT count(*)::int total,
           count(producer_id)::int prod,
           count(lwin)::int lwin,
           count(*) FILTER (WHERE producer_id IS NOT NULL AND lwin IS NOT NULL)::int both,
           count(taste_text)::int taste,
           count(*) FILTER (WHERE taste_text IS NOT NULL AND lwin IS NOT NULL)::int taste_lwin
      FROM wine.listings WHERE source = 'systembolaget'`))[0];
  L.push(table(["join", "matched", "of", "rate"], [
    ["listing -> producer", ls.prod, ls.total, pct(ls.prod, ls.total)],
    ["listing -> lwin (wine)", ls.lwin, ls.total, pct(ls.lwin, ls.total)],
    ["listing -> lwin, given a producer match", ls.both, ls.prod, pct(ls.both, ls.prod)],
    ["Swedish tasting note -> lwin", ls.taste_lwin, ls.taste, pct(ls.taste_lwin, ls.taste)],
  ]));
  L.push("");
  L.push(`Wine-match methods: ${JSON.stringify(notes("load-systembolaget").wine_methods ?? {})}`);
  L.push("");
  L.push(`Producer-match methods: ${JSON.stringify(notes("load-systembolaget").producer_methods ?? {})}`);
  L.push("");

  L.push("### Producer links (Wikidata, Exa, trade bodies)");
  L.push("");
  const pl = notes("load-producer-links");
  const plRows: Array<Array<string | number>> = [];
  for (const key of ["wikidata", "exa-producers", "trade-bodies"]) {
    const b = pl[key];
    if (!b) continue;
    plRows.push([key, b.rows ?? "-", b.matched ?? "-", pct(b.matched ?? 0, b.rows ?? 0)]);
  }
  L.push(table(["source", "rows in", "matched to a producer", "rate"], plRows));
  L.push("");
  const live = await q(pool, `SELECT source, count(*)::int c, count(DISTINCT producer_id)::int p FROM wine.producer_links GROUP BY 1 ORDER BY 2 DESC`);
  L.push(table(["producer_links.source", "link rows", "distinct producers"], live.map((r) => [`\`${r.source}\``, r.c, r.p])));
  L.push("");
  const bodies = (pl["trade-bodies"]?.per_body ?? {}) as Record<string, any>;
  const bodyRows = Object.entries(bodies)
    .sort((a, b) => (b[1].rows ?? 0) - (a[1].rows ?? 0))
    .map(([slug, b]) => [slug, b.country ?? "-", b.rows ?? 0, b.matched ?? 0, pct(b.matched ?? 0, b.rows ?? 0)]);
  if (bodyRows.length) {
    L.push("Per trade body:");
    L.push("");
    L.push(table(["body", "country", "rows", "matched", "rate"], bodyRows));
    L.push("");
  }

  L.push("### Wikidata wines");
  L.push("");
  const ww = notes("load-wikidata-wines");
  L.push(table(["measure", "value"], [
    ["rows in", ww.labelled_rows ?? n("load-wikidata-wines", "rows_in")],
    ["GI-suffix labels skipped (denominations, not wines)", ww.gi_labels_skipped ?? "-"],
    ["real wine labels", ww.wine_labels ?? "-"],
    ["matched to an LWIN", ww.wine_names_out ?? "-"],
    ["rate of wine labels", ww.match_rate_of_wine_labels ?? "-"],
    ["wine_grapes written", ww.wine_grapes_out ?? "-"],
  ]));
  L.push("");

  L.push("### Wines -> appellations, by country (Live only)");
  L.push("");
  const byCountry = await q(pool, `
    SELECT coalesce(country,'(none)') country,
           count(*)::int total,
           count(appellation_id)::int resolved,
           count(*) FILTER (WHERE appellation_match = 'sub_region')::int sub_region,
           count(*) FILTER (WHERE appellation_match = 'site')::int site,
           count(*) FILTER (WHERE appellation_match = 'region')::int region,
           count(*) FILTER (WHERE appellation_id IS NOT NULL AND EXISTS (
             SELECT 1 FROM wine.appellations a WHERE a.id = wines.appellation_id AND a.source = 'lwin'))::int synthetic
      FROM wine.wines WHERE status = 'Live' GROUP BY 1 HAVING count(*) >= 100 ORDER BY 2 DESC`);
  L.push(table(["country", "Live wines", "resolved", "rate", "sub_region", "site", "region", "of which synthetic"],
    byCountry.map((r) => [r.country, r.total, r.resolved, pct(r.resolved, r.total), r.sub_region, r.site, r.region, r.synthetic])));
  L.push("");
  const ra = notes("resolve-appellations");
  L.push(`EU-register countries, Live: ${ra.eu_live_resolved ?? "-"} / ${ra.eu_live ?? "-"} = ${ra.eu_live_pct ?? "-"}%. Ambiguous name_norms decided by PDO-over-PGI: ${ra.tie_count ?? "-"} distinct names.`);
  L.push("");
  L.push(`Synthetic non-EU appellation rows: ${ra.synthetic_appellations ?? "-"}, one per place. ${ra.synthetic_places_with_mixed_designations ?? "-"} of those places carry more than one LWIN designation (Paso Robles is filed as AVA, DO and AOP); the gi_type and source_ref take the designation most of the place's wines carry. Where eAmbrosia already protects a third-country name - Napa Valley (PDO), Willamette Valley (PGI) - the register row wins and no synthetic row is made.`);
  L.push("");
  L.push(`LWIN alias rows inserted into \`appellation_names\`: ${ra.curated_aliases ?? "-"} curated, ${ra.generated_type_suffix_aliases ?? "-"} generated by stripping a trailing wine-type word. Curated entries that found no register row: ${JSON.stringify(ra.curated_alias_misses ?? [])}.`);
  L.push("");

  L.push("### Grapes");
  L.push("");
  const ag = (await q(pool, `SELECT count(*)::int total, count(grape_id)::int resolved FROM wine.appellation_grapes`))[0];
  const wgr = (await q(pool, `SELECT count(*)::int total, count(grape_id)::int resolved FROM wine.wine_grapes`))[0];
  L.push(table(["join", "resolved", "of", "rate"], [
    ["appellation_grapes -> grapes (register spellings)", ag.resolved, ag.total, pct(ag.resolved, ag.total)],
    ["wine_grapes -> grapes (Systembolaget + Wikidata spellings)", wgr.resolved, wgr.total, pct(wgr.resolved, wgr.total)],
  ]));
  L.push("");
  L.push(`appellation_grapes stages: ${JSON.stringify(notes("load-grapes").stages ?? {})}`);
  L.push("");
  L.push(`wine_grapes stages: ${JSON.stringify(notes("resolve-wine-grapes").stages ?? {})}`);
  L.push("");

  L.push("### Rule documents");
  L.push("");
  const docs = await q(pool, `
    SELECT doc_type, country, count(*)::int total, count(appellation_id)::int matched
      FROM wine.appellation_documents GROUP BY 1,2 ORDER BY 3 DESC`);
  L.push(table(["doc type", "country", "documents", "matched to an appellation", "rate"],
    docs.map((r) => [r.doc_type, r.country, r.total, r.matched, pct(r.matched, r.total)])));
  L.push("");
  const appWithDoc = (await q(pool, `
    SELECT count(DISTINCT appellation_id)::int c,
           (SELECT count(*)::int FROM wine.appellations WHERE source <> 'lwin') a
      FROM wine.appellation_documents WHERE appellation_id IS NOT NULL`))[0];
  L.push(`Register appellations with at least one rule document: ${appWithDoc.c} / ${appWithDoc.a} = ${pct(appWithDoc.c, appWithDoc.a)}. The three ministries publish FR, IT and ES only.`);
  L.push("");

  L.push("### Search vectors");
  L.push("");
  const sv = await q(pool, `
    SELECT 'producers' t, count(*)::int total, count(search_vector)::int filled FROM wine.producers
    UNION ALL SELECT 'wines', count(*), count(search_vector) FROM wine.wines
    UNION ALL SELECT 'listings', count(*), count(search_vector) FROM wine.listings
    UNION ALL SELECT 'appellations', count(*), count(search_vector) FROM wine.appellations
    UNION ALL SELECT 'grapes', count(*), count(search_vector) FROM wine.grapes
    UNION ALL SELECT 'appellation_documents', count(*), count(search_vector) FROM wine.appellation_documents`);
  L.push(table(["table", "rows", "search_vector set"], sv.map((r) => [r.t, r.total, r.filled])));
  L.push("");

  // ---- 4. top unmatched ----------------------------------------------
  L.push("## Top unmatched");
  L.push("");
  L.push("### Wines with no appellation (Live, top 40 by count)");
  L.push("");
  const tu = (ra.top_unmatched ?? []) as Array<any>;
  L.push(table(["country", "region", "sub_region", "wines"],
    tu.map((r) => [r.country || "-", r.region || "-", r.sub_region || "-", r.wines])));
  L.push("");
  L.push("### wine_grapes spellings with no grape (top 20)");
  L.push("");
  const tg = (notes("resolve-wine-grapes").top_unresolved ?? []) as Array<any>;
  L.push(table(["grape_name_raw", "rows"], tg.map((r) => [r.name, r.rows])));
  L.push("");
  L.push("### appellation_grapes spellings with no grape (top 20)");
  L.push("");
  const agTop = await q(pool, `
    SELECT grape_name_raw, count(*)::int c FROM wine.appellation_grapes
     WHERE grape_id IS NULL GROUP BY 1 ORDER BY 2 DESC LIMIT 20`);
  L.push(table(["grape_name_raw", "rows"], agTop.map((r) => [r.grape_name_raw, r.c])));
  L.push("");

  // ---- 5. what would move each rate ----------------------------------
  L.push("## What would move each rate");
  L.push("");
  L.push("Taken from the loaders' own notes, not from guesswork.");
  L.push("");
  L.push([
    "- **Wines -> appellations, non-EU (US 83%, NZ 13%, AR 0%, MX 0%, LB/IL/GE 0%).** A synthetic row is only",
    "  created where LWIN carries a *designation*. Argentina, New Zealand, Mexico, Lebanon, Israel and Georgia",
    "  have almost none in the LWIN DESIGNATION column, so Mendoza, Marlborough and Valle de Guadalupe get",
    "  nothing. Moving this means a per-country GI list (TTB for the remaining US AVAs, Wine Australia GIs,",
    "  INV for Argentina, NZ GI schedule) loaded as real appellation rows - not a looser resolver.",
  ].join("\n"));
  L.push([
    "- **Wines -> appellations, EU remainder (5,557 Live).** The largest bucket is wines with no region and no",
    "  sub_region at all (FR 2,385, IT 753, ES 408, AT 242, DE 146): LWIN simply does not say where they are",
    "  from, so nothing in this database can place them. Of the rest, the named blockers are the LWIN regions",
    "  that span several register names and were deliberately left alone: ES \"Castilla La Mancha\" (Castilla PGI",
    "  vs La Mancha PDO), PT \"Beiras\", HR \"Dalmacija\", and BG \"Thracian Lowlands\" / GR \"Pangeon\" / DE \"Rhein\",",
    "  which have no register row at all. Each needs a decision, not code.",
  ].join("\n"));
  L.push([
    "- **The `site` stage never fires (0 rows).** It is kept because it is correct, but LWIN files the Alsace",
    "  grand cru lieux-dits in SUB_REGION rather than SITE, and every string that reaches SITE is a Burgundy",
    "  climat (\"Morgeot\", \"Les Suchots\") whose sub_region has already matched the village PDO. Climats are not",
    "  separately protected names, so there is nothing in the register for them to hit. A premier-cru climat",
    "  layer would need INAO's climat list, which is a new source, not a new stage.",
  ].join("\n"));
  L.push([
    "- **appellation_grapes -> grapes (88.8%).** load-grapes.ts reports that none of the 30 most frequent",
    "  unresolved register spellings (Malbech, Carignano, Olasz Rizling, Rulandske Modre...) appears anywhere in",
    "  the Wikidata aliases column, so `scripts/wine/grape-synonyms.json` is live but empty. This moves only with",
    "  a second synonym authority - VIVC's own synonym export, or the national catalogues - not with fuzzier",
    "  matching, which was tried and rejected below 0.7.",
  ].join("\n"));
  L.push([
    "- **wine_grapes -> grapes (97.7%).** The 18 remaining spellings are regional synonyms Wikidata does not",
    "  carry as aliases (Mazuelo = Carignan, Aragonez = Tempranillo, Tinto fino / Tinta del pais / Tinta de toro",
    "  = Tempranillo, Rolle = Vermentino, Sangiovese grosso = Sangiovese) plus one Systembolaget field that holds",
    "  an appellation, not a grape (\"Barolo DOCG\"). A hand-verified synonym file of about twenty entries closes",
    "  most of it.",
  ].join("\n"));
  L.push([
    "- **Systembolaget -> LWIN (41.6%).** load-systembolaget.ts reports 69.2% of producer-matched rows also match",
    "  a wine, so the ceiling is the producer match (60.1%), not the wine match. The unmatched producer samples",
    "  are importers and agents rather than wineries (\"Mondowine AB\", \"137:ans Beer & Spirits\", \"Flera",
    "  producenter\"), and the unmatched wine samples are supermarket labels with no LWIN entry (\"19 Crimes /",
    "  Sauv Block\"). Both are ceilings of the two catalogues, not of the matcher.",
  ].join("\n"));
  L.push([
    "- **Wikidata wineries -> producers (48.3%).** The 958 unmatched samples are small growers, Heurigen and",
    "  co-operatives that LWIN never lists, plus a handful of vineyard sites filed as wineries",
    "  (\"Batard-Montrachet\"). LWIN's coverage is the ceiling.",
  ].join("\n"));
  L.push([
    "- **Exa -> producers (97.8%).** load-producer-links.ts names the 11 misses: cognac and grappa houses, which",
    "  LWIN files as TYPE=Spirit and load-lwin.ts therefore skips. Nothing to fix.",
  ].join("\n"));
  L.push([
    "- **Trade bodies -> producers (35.8% overall, 7.3% for Jura).** The low bodies are French and Italian",
    "  appellation directories full of small growers with no LWIN row, and directories whose extracted name is a",
    "  legal entity rather than the trading name. Per-body rates are in the table above; the bodies worth a",
    "  second extraction pass are the ones with many rows and a low rate, not the ones with a low rate and few",
    "  rows.",
  ].join("\n"));
  L.push([
    "- **Rule documents (99.5% matched).** Coverage, not matching, is the gap: only FR, IT and ES ministries",
    "  publish machine-readable rule texts, so every other register country has appellations with no quotable",
    "  clause.",
  ].join("\n"));
  L.push("");

  writeFileSync(OUT, L.join("\n") + "\n", "utf8");
  console.log(`wrote ${OUT} (${L.join("\n").length} bytes)`);
  await logLoad(pool, "join-report", { rows_out: L.length }, { path: "docs/wine-bore-join-report.md" });
  await pool.end();
}

main().catch((e) => { console.error(e); process.exit(1); });
